# Generated by Django 5.2.8 on 2025-12-12 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="followers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
